export interface Contact {
  person_type?: string;
  name: string;
  identity_card?: string;
  cpf?: string;
  email: string;
  cell_phone?: string;
  zip_code?: string;
  address?: string;
  number?: string;
  complement?: string;
  neighborhood?: string;
  city?: string;
  state?: string;
  company_name?: string;
  cnpj?: string;
  state_registration?: string;
  billing_zip_code?: string;
  billing_address?: string;
  billing_number?: string;
  billing_complement?: string;
  billing_neighborhood?: string;
  billing_city?: string;
  billing_state?: string;
  different_billing_address?: boolean;
  status?: string;
  created_at?: Date;
  updated_at: Date;
}
