name: Arte Arena Space Client Frontend - Production CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  deploy_to_production:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Setup Environment for Production
        run: |
          image_name=artearenahub/space-frontend-client
          echo "image_name=$image_name" >> $GITHUB_ENV
          tag_name="$image_name:0.0.${{ github.run_number }}"
          echo "tag_name=$tag_name" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_API=https://api.my.spacearena.net" > .env
          echo "image_tag=$image_name:0.0.${{ github.run_number }}" >> $GITHUB_ENV
          echo "image_tag_latest=$image_name:latest" >> $GITHUB_ENV
          echo "Environment: Production"
          echo "Image Tag: ${{ env.tag_name }}"
          echo "Image Tag Latest: ${{ env.image_tag_latest }}"
          echo "Environment file content:"
          cat .env

      - name: Ensure .env is included
        run: |
          ls -la
          if [ ! -f ".env" ]; then
            echo "Error: .env file was not created"
            exit 1
          fi

      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}

      - name: Build and push Docker frontend client image (Production)
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: |
            ${{ env.tag_name }}
            ${{ env.image_name }}:latest
        env:
          ACTIONS_RUNNER_DEBUG: true
          ACTIONS_STEP_DEBUG: true